# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/00_dbdev',
                'doc_host': 'https://nitesh.github.io',
                'git_url': 'https://github.com/nitesh/00_dbdev',
                'lib_path': '00_dbdev'},
  'syms': {'00_dbdev.core': {'00_dbdev.core.foo': ('core.html#foo', '00_dbdev/core.py')}}}
